import type { TFunction } from "i18next";

const errorKeys = {
  task_model_not_configured: "home:action_error_model",
  task_model_configuration_invalid: "home:action_error_model",
  prepared_action_expired: "home:action_error_expired",
  agent_session_changed: "home:action_error_expired",
  studio_transcription_draft_changed: "home:action_error_changed",
  studio_transcription_existing_drafts: "home:action_error_drafts",
  studio_translation_plan_has_no_ready_documents: "home:action_error_documents",
  studio_translation_not_admitted: "home:action_error_documents",
  agent_cancelled: "home:action_dismissed",
  prepared_action_failed: "home:action_error_failed",
  tool_request_failed: "home:action_error_failed",
  revision_conflict: "studio:errors.revision_conflict",
  document_unavailable: "studio:errors.document_unavailable",
  needs_configuration: "studio:errors.needs_configuration",
  translation_failed: "studio:errors.translation_failed",
  transcription_failed: "studio:errors.transcription_failed",
  prepared_action_limit: "home:action_error_limit",
  invalid_tool_arguments: "home:action_error_arguments",
  studio_transcription_not_admitted: "home:action_error_changed",
  studio_transcription_submission_unknown: "home:action_error_submission_unknown",
  studio_translation_submission_unknown: "home:action_error_submission_unknown",
  access_denied: "studio:errors.access_denied",
  studio_transcription_not_ready: "home:action_error_changed",
  unsupported_feature: "studio:errors.unsupported_feature",
  limit_exceeded: "studio:errors.limit_exceeded",
  rename_confirmation_required: "home:action_error_rename_confirmation",
  rename_not_applied: "home:action_error_rename_not_applied",
  rename_plan_expired: "home:action_error_rename_expired",
  rename_plan_empty: "home:action_error_rename_empty",
  rename_plan_changed: "home:action_error_rename_changed",
  rename_apply_outcome_unknown: "home:action_error_rename_unknown",
  rename_plan_failed: "home:action_error_rename_plan",
  rename_inspect_failed: "home:action_error_rename_inspect",
  translation_requires_picker: "home:action_error_picker_required",
  translation_input_selection_cancelled: "home:action_error_selection_cancelled",
  recovery_selection_cancelled: "home:action_error_selection_cancelled",
  translation_output_selection_cancelled: "home:action_error_output_cancelled",
  recovery_output_selection_cancelled: "home:action_error_output_cancelled",
  output_selection_cancelled: "home:action_error_output_cancelled",
  translation_input_authorization_failed: "home:action_error_authorization",
  translation_output_authorization_failed: "home:action_error_authorization",
  recovery_output_authorization_unavailable: "home:action_error_authorization",
  agent_stopped_before_queue: "home:action_error_stopped",
  scan_failed: "home:action_error_scan",
} as const;

export function actionErrorMessage(error: string, t: TFunction): string {
  return Object.prototype.hasOwnProperty.call(errorKeys, error)
    ? t(errorKeys[error as keyof typeof errorKeys]) : error;
}
