// This policy is maintenance metadata, never a dependency of the Studio runtime.
export const SOURCE_COMMIT = '3a0f50ed15c1b63451402cecf27240182235e567';
export const BASELINE_PATH = 'resources/subtitle-studio/provenance/transcription-baseline.json';

const copy = (prefix, destination, category, reason) => ({ prefix, destination, category, disposition: 'planned-copy', reason });
const evidence = (source, category, reason) => ({ source, destination: null, category, disposition: 'reference-only', follow: false, reason });
// Bind computed-loader reviews to the exact code that established their targets.
// A new source commit must renew this audit if even the surrounding path setup changes.
const dynamicSourceSha256 = {
  'electron/main/local-subtitle/overwrite-native-backend.ts': '158a2c3a0d52f5da2f3f255234e48954db9ed4f5ad4cda9f3ed0c37d4325d73d',
  'scripts/local-subtitle/overwrite-native/build-addon-macos-arm64.test.mjs': 'ca823b4527de7835b177ca703447b7cb3a677dc6695d10e4e5f25358edf9e3b6',
  'scripts/local-subtitle/overwrite-native/run-addon-integration.mjs': 'ddb235eb4ed3a255f9836fb39897261be31f20f9e9597633292b0d5d98e8e7ad',
  'scripts/local-subtitle/overwrite-native/run-addon-recovery-child.mjs': 'f9ff8b27d571fdb0d92ad1dc5ec7fa1125df3ba4f472942ec8f3c3e28c208122',
  'scripts/local-subtitle/overwrite-native/run-addon-recovery-integration.mjs': '1bf1159442f03475b154fc9c757be8a7978b46607fd832532ac368bd9535a82d',
  'scripts/local-subtitle/overwrite-native/run-addon-windows-integration.mjs': '9948488fc85bae9ccfbad82d92f904d58886aa3f25586713d3eea6b791f3b4d0',
  'scripts/local-subtitle/overwrite-native/run-addon-windows-recovery-child.mjs': '8c336f55f88c0df62e2641c7f857fcfa37d820e2cec64cd7d1f872d23ba5b191',
  'scripts/local-subtitle/overwrite-native/run-addon-windows-recovery-integration.mjs': '5d243610b91e7fb00683f17f5347976b4c351f603f802a7d6fb614e72aba6a89',
  'scripts/local-subtitle/runtime/electron-builder-local-subtitle-before-pack.cjs': '2cc7e8252e412e841a4c7b814cc73ce7bfb4db51be2781c5657e5ed54cd1a154',
  'scripts/local-subtitle/runtime/electron-builder-pre005-before-pack.cjs': '0d310c2437b8ceaa9dbee5d5e0e3d279ca766d8c881ea4e11b23069d8be7dad8',
};

export const POLICY = {
  version: 1,
  roots: [
    'electron/main/local-subtitle/', 'resources/local-subtitle/', 'native/local-subtitle-overwrite/',
    'scripts/local-subtitle/runtime/', 'scripts/local-subtitle/overwrite-native/',
    'scripts/local-subtitle/whisper-server/', 'test/local-subtitle/',
    'src/type/localSubtitle.ts', 'src/type/localSubtitleIpc.ts',
    'src/type/localSubtitle.test.ts', 'src/type/localSubtitleIpc.test.ts',
    'src/store/tools/subtitle/localSubtitleTranscriberConfig.ts',
    'src/store/tools/subtitle/localSubtitleTranscriberConfig.test.ts',
    'electron/main/index.ts', 'electron/preload/index.ts', 'electron/preload/local-subtitle-api.ts',
    'electron/preload/local-subtitle-channel-policy.ts',
    'src/store/tools/subtitle/useLocalSubtitleTranscriberStore.ts',
    'src/services/local-subtitle/', 'src/pages/Tools/Subtitle/LocalSubtitleTranscriber/index.tsx',
    'electron-builder.json', 'package.json', 'pnpm-lock.yaml', 'vite.config.ts',
  ],
  rules: [
    copy('electron/main/local-subtitle/', 'electron/main/subtitle-studio/transcription/native/', 'main-process', 'Freeze lifecycle, native ownership and transcription closure before replacing legacy output semantics.'),
    { ...copy('resources/local-subtitle/manifests/', 'resources/subtitle-studio/transcription/manifests/', 'resource-manifest', 'Preserve expected pins; proposed filename removes the old owner identity, while schema/value changes require later review.'), renameBasename: { from: 'local-subtitle-', to: 'subtitle-studio-' } },
    copy('resources/local-subtitle/', 'resources/subtitle-studio/transcription/', 'resource-identity', 'Preserve expected pins and existing license status; no installed binary is inspected or verified.'),
    copy('native/local-subtitle-overwrite/', 'native/subtitle-studio-overwrite/', 'native-source', 'Preserve native source; names, transaction prefixes and signing identity require a separate namespace review.'),
    copy('scripts/local-subtitle/runtime/', 'scripts/subtitle-studio/transcription/runtime/', 'runtime-tooling', 'Freeze build/validation tooling; new packaging composition must replace single-resource assumptions.'),
    copy('scripts/local-subtitle/overwrite-native/', 'scripts/subtitle-studio/transcription/overwrite-native/', 'native-tooling', 'Freeze reproducible native build and isolated validation sources without running them.'),
    copy('scripts/local-subtitle/whisper-server/', 'scripts/subtitle-studio/transcription/whisper-server/', 'runtime-validation', 'Retain validation helpers as proposed test/tool sources, not evidence that any native check passed.'),
    copy('test/local-subtitle/', 'test/subtitle-studio/transcription/', 'test', 'Retain deterministic and native test sources without claiming execution or equivalence.'),
    copy('scripts/local-subtitle/benchmark/', 'scripts/subtitle-studio/transcription/test-support/', 'test-helper', 'Only helpers reached from selected code are included; inclusion does not adopt experimental algorithms.'),
    copy('docs/v0.2.11/local-subtitle-transcriber/poc/', 'test/subtitle-studio/transcription/fixtures/poc/', 'historical-fixture', 'Only actual test dependencies are frozen as future fixtures; old documentation is not a runtime dependency.'),
    ...['artifact-handoff.ts', 'subtitle-artifact-registry.ts', 'subtitle-exporter.ts', 'subtitle-formats.ts', 'production-executor.ts', 'job-manager.ts', 'overwrite-production-runtime.ts', 'overwrite-transaction.ts', 'overwrite-directory-coordinator.ts', 'overwrite-recovery-owner.ts', 'overwrite-recovery-ipc.ts', 'overwrite-native-backend.ts', 'overwrite-native-resource.ts', 'overwrite-native-host-preflight.ts'].map(name => ({ source: `electron/main/local-subtitle/${name}`, destination: `electron/main/subtitle-studio/transcription/native/${name}`, category: 'legacy-output-boundary', disposition: 'planned-copy-then-adapt', reason: 'Retain the conservative replay closure first; replace artifact/output/overwrite result semantics with a document sink and prune unused output machinery only after equivalence checks.' })),
    { source: 'src/type/localSubtitle.ts', destination: 'src/subtitle-studio/transcription/domain.ts', category: 'domain', disposition: 'planned-copy-then-adapt', reason: 'Retain inference contract and limits; replace legacy output/task ownership after deterministic replay.' },
    { source: 'src/type/localSubtitleIpc.ts', destination: 'src/subtitle-studio/transcription/ipc-contract.ts', category: 'ipc-contract', disposition: 'planned-copy-then-adapt', reason: 'Retain input validation; new public channels and branded owners need an independent contract.' },
    { source: 'src/store/tools/subtitle/localSubtitleTranscriberConfig.ts', destination: 'src/subtitle-studio/transcription/config.ts', category: 'effective-defaults', disposition: 'planned-copy-then-adapt', reason: 'Freeze actual sanitized user defaults; replace output and post-action fields at the document boundary.' },
    { source: 'src/type/localSubtitle.test.ts', destination: 'test/subtitle-studio/transcription/domain.test.ts', category: 'test', disposition: 'planned-copy', reason: 'Retain production contract assertions and their frozen fixture.' },
    { source: 'src/type/localSubtitleIpc.test.ts', destination: 'test/subtitle-studio/transcription/ipc-contract.test.ts', category: 'test', disposition: 'planned-copy-then-adapt', reason: 'Retain input validation and independently rewrite new namespace assertions.' },
    { source: 'src/store/tools/subtitle/localSubtitleTranscriberConfig.test.ts', destination: 'test/subtitle-studio/transcription/config.test.ts', category: 'test', disposition: 'planned-copy', reason: 'Freeze real preference sanitization tests.' },
    evidence('electron/main/index.ts', 'application-composition', 'Record actual service construction and registration; do not copy the application or old translation coupling.'),
    evidence('electron/preload/index.ts', 'application-composition', 'Record the legacy bridge contribution without copying unrelated preload APIs.'),
    evidence('electron/preload/local-subtitle-api.ts', 'legacy-ipc-boundary', 'Reference for a future independent fixed public/internal API; no new IPC is implemented yet.'),
    evidence('electron/preload/local-subtitle-channel-policy.ts', 'legacy-ipc-boundary', 'Reference only until the new public channel contract is specified.'),
    evidence('src/store/tools/subtitle/useLocalSubtitleTranscriberStore.ts', 'legacy-state-boundary', 'Record versioned defaults migration; do not reuse the old persisted key, queue or runtime owner.'),
    { prefix: 'src/services/local-subtitle/', destination: null, category: 'legacy-renderer-boundary', disposition: 'reference-only', follow: false, reason: 'Reference old observation/resource APIs and identify translation handoff for replacement; do not traverse the old frontend graph.' },
    evidence('src/pages/Tools/Subtitle/LocalSubtitleTranscriber/index.tsx', 'legacy-ui-boundary', 'Record user configuration consumption; build the new producer in Studio rather than copying the old page.'),
    ...['electron-builder.json', 'package.json', 'pnpm-lock.yaml', 'vite.config.ts'].map(source => evidence(source, 'build-composition', 'Record dependency/build/resource composition; preserve the existing lock and do not copy application configuration wholesale.')),
    ...['legacyIpcBridge.test.ts', 'preloadApi.test.ts', 'preloadChannelPolicy.test.ts'].map(name => evidence(`test/local-subtitle/${name}`, 'legacy-test-boundary', 'Keep as v1 coexistence evidence; defer new-namespace rewrite and do not traverse the unrelated old IPC graph.')),
    ...['run-poc.mjs', 'poc-metrics.test.mjs'].map(name => evidence(`scripts/local-subtitle/whisper-server/${name}`, 'historical-poc', 'Record earlier PoC behavior without adopting its inference pipeline or proposing its copy.')),
    { source: 'scripts/local-subtitle/whisper-server/supervisor.test.mjs', destination: 'scripts/subtitle-studio/transcription/whisper-server/supervisor.test.mjs', category: 'test-adaptation', disposition: 'planned-copy-then-adapt', reason: 'Preserve supervisor assertions, but remove or independently extract the PoC sample/CLI helper assertions imported from reference-only run-poc.mjs.' },
    { source: 'test/local-subtitle/overwriteProductionRuntime.test.ts', destination: 'test/subtitle-studio/transcription/overwriteProductionRuntime.test.ts', category: 'test-adaptation', disposition: 'planned-copy-then-adapt', reason: 'Rewrite the source-reading assertion against the future Studio composition entry; do not retain its reference-only electron/main/index.ts dependency.' },
    ...['generate-electron-builder-spike.mjs', 'generate-electron-builder-spike.test.mjs', 'sign-packaged-spike.mjs', 'sign-packaged-spike.test.mjs', 'sign-packaged-spike-windows.mjs', 'sign-packaged-spike-windows.test.mjs', 'electron-builder-pre005-before-pack.cjs', 'electron-builder-pre005-before-pack-legacy.test.mjs'].map(name => evidence(`scripts/local-subtitle/runtime/${name}`, 'historical-packaging-reference', 'Retain historical signing/spike compatibility evidence; the new packaging composition must be designed independently.')),
  ],
  excludedScopes: [
    { prefix: 'scripts/local-subtitle/benchmark/', reason: 'Research and unadopted experiments are excluded unless required transitively as a selected test helper.' },
    { prefix: 'test-results/', reason: 'Private captures and audio are neither read nor assumed available.' },
  ],
  externalPackages: ['@electron/osx-sign'],
  dynamicAudits: [
    { source: 'electron/main/local-subtitle/overwrite-native-backend.ts', expression: 'createRequire(import.meta.url)(absoluteNodePath)', targets: [], reason: 'Loads only a previously verified owner-bound native addon path. Binary is represented by the overwrite manifest; never load it during provenance generation.' },
    { source: 'scripts/local-subtitle/runtime/electron-builder-local-subtitle-before-pack.cjs', expression: 'import(moduleUrl)', targets: ['scripts/local-subtitle/runtime/runtime-manifest.mjs', 'scripts/local-subtitle/overwrite-native/overwrite-native-staging.mjs', 'scripts/local-subtitle/runtime/validate-runtime-staging.mjs'], reason: 'Three local pathToFileURL loader sites form the explicit beforePack validation closure.' },
    { source: 'scripts/local-subtitle/runtime/electron-builder-pre005-before-pack.cjs', expression: 'import(moduleUrl)', targets: ['scripts/local-subtitle/runtime/runtime-manifest.mjs'], reason: 'Historical wrapper resolves its sibling runtime verifier; retained as tooling compatibility evidence.' },
    ...[
      ['run-addon-windows-integration.mjs', 'require(canonicalAddonPath)'],
      ['run-addon-recovery-child.mjs', 'require(input.addonPath)'],
      ['run-addon-windows-recovery-child.mjs', 'require(input.addonPath)'],
      ['run-addon-recovery-integration.mjs', 'require(canonicalAddonPath)'],
      ['run-addon-integration.mjs', 'require(canonicalAddonPath)'],
      ['build-addon-macos-arm64.test.mjs', 'require(outputPath)'],
      ['run-addon-windows-recovery-integration.mjs', 'require(canonicalAddonPath)'],
      ['run-addon-windows-recovery-integration.mjs', 'require(addonPath)'],
    ].map(([name, expression]) => ({ source: `scripts/local-subtitle/overwrite-native/${name}`, expression, targets: [], reason: 'Isolated native-test loader consumes its explicitly prepared addon artifact; artifact bytes are not a tracked source dependency and are not loaded here.' })),
  ].map(audit => ({ ...audit, sourceSha256: dynamicSourceSha256[audit.source] })),
  runtimeReferences: [
    { source: 'test/local-subtitle/runtimeFixture.ts', prefix: 'resources/local-subtitle/licenses/', reason: 'Fixture reads license/source-offer files by string paths.' },
    { source: 'scripts/local-subtitle/runtime/staging-contract.mjs', prefix: 'resources/local-subtitle/manifests/', reason: 'String-based strict staging contract loaders and pins.' },
    { source: 'scripts/local-subtitle/overwrite-native/overwrite-staging-contract.mjs', targets: ['resources/local-subtitle/manifests/local-subtitle-overwrite-staging.v1.json'], reason: 'String-based overwrite contract loader.' },
    { source: 'scripts/local-subtitle/runtime/windows-cuda-pack-contract.mjs', targets: ['resources/local-subtitle/manifests/local-subtitle-windows-cuda-pack.v1.json'], reason: 'String-based CUDA pack contract loader.' },
    ...['stage-runtime.mjs', 'stage-runtime-windows-x64.mjs'].map(name => ({ source: `scripts/local-subtitle/runtime/${name}`, prefix: 'resources/local-subtitle/licenses/', reason: 'Runtime staging copies pinned license/source-offer files by string-based paths.' })),
    ...['run-native002-macos-smoke.mjs', 'run-native002-windows-smoke.mjs'].map(name => ({ source: `scripts/local-subtitle/runtime/${name}`, targets: ['resources/local-subtitle/manifests/local-subtitle-models.v1.json'], reason: 'Native smoke reads the tracked model catalog by an explicit repository-relative string path.' })),
    { source: 'scripts/local-subtitle/overwrite-native/build-addon-macos-arm64.mjs', prefix: 'native/local-subtitle-overwrite/', reason: 'Native compilation recipe reads C++ source and build configuration.' },
    { source: 'scripts/local-subtitle/overwrite-native/build-addon-windows-x64.mjs', prefix: 'native/local-subtitle-overwrite/', reason: 'Native compilation recipe also reads the Windows delay-load hook.' },
  ],
  snapshots: [
    { source: 'src/type/localSubtitle.ts', symbols: ['LOCAL_SUBTITLE_PRODUCTION_CONTRACT', 'LOCAL_SUBTITLE_LIMITS', 'LOCAL_SUBTITLE_WINDOW_STRATEGIES'] },
    { source: 'src/store/tools/subtitle/localSubtitleTranscriberConfig.ts', symbols: ['DEFAULT_LOCAL_SUBTITLE_TRANSCRIBER_PREFERENCES', 'DEFAULT_LOCAL_SUBTITLE_TRANSCRIBER_DRAFT_PREFERENCES'] },
  ],
  manualAudits: [
    { sources: ['src/store/tools/subtitle/localSubtitleTranscriberConfig.ts', 'src/store/tools/subtitle/useLocalSubtitleTranscriberStore.ts', 'src/type/localSubtitleIpc.ts'], concern: 'Effective defaults', decision: 'Freeze user defaults and sanitizer: acoustic_quiet_v1 forces VAD; old store version<4 migration is reference evidence, not a new persisted-state migration.' },
    { sources: ['electron/main/local-subtitle/production-executor.ts', 'electron/main/local-subtitle/job-manager.ts', 'electron/main/local-subtitle/artifact-handoff.ts'], concern: 'Document sink and output replacement', decision: 'Replace artifact output only after final separator restoration and cleanup/cancellation checks. Preserve rich transcript and independently migrate result/IPC semantics.' },
    { sources: ['electron/main/local-subtitle/overwrite-native-host-preflight.ts', 'scripts/local-subtitle/overwrite-native/overwrite-staging.mjs'], concern: 'Embedded child-process JavaScript', decision: 'String-embedded require(process.argv[1]) loads the explicitly prepared addon only in an isolated Electron/native validation child. Static import analysis cannot prove this binary boundary.' },
    { sources: ['native/local-subtitle-overwrite/src/addon.cc', 'native/local-subtitle-overwrite/src/addon-win32.cc', 'scripts/local-subtitle/overwrite-native/overwrite-staging-contract.mjs'], concern: 'Native names and transaction identity', decision: 'Old .fusionkit-local-subtitle-/.fusionkit-overwrite prefixes, logical addon names, recipe receipt and codesign identity require separate renaming/validation. Do not globally replace schema IDs or semantic contract strings.' },
    { sources: ['electron-builder.json', 'scripts/local-subtitle/runtime/validate-runtime-staging.mjs', 'scripts/local-subtitle/runtime/electron-builder-local-subtitle-before-pack.cjs'], concern: 'Dual resources and signing', decision: 'Existing validator/hook assume one extraResources entry and strict signIgnore shape. Introduce a real composition hook later; do not weaken the old validator.' },
    { sources: ['electron/main/local-subtitle/server-supervisor.ts', 'electron/main/local-subtitle/resource-path.ts', 'electron/main/local-subtitle/backend-resolver.ts', 'electron/main/local-subtitle/accelerator-manager.ts', 'electron/main/local-subtitle/media-normalizer.ts', 'electron/main/local-subtitle/server-session.ts', 'electron/main/local-subtitle/production-executor.ts', 'electron/main/local-subtitle/job-manager.ts', 'electron/main/local-subtitle/overwrite-native-resource.ts', 'electron/main/local-subtitle/overwrite-recovery-owner.ts', 'electron/main/local-subtitle/overwrite-transaction.ts'], concern: 'Module identity and ownership', decision: 'Independent module copies must create their own Symbol/WeakSet/WeakMap brands (including PCM/window proofs) and reject old proofs; same source digest does not prove isolated ownership.' },
  ],
  limitations: [
    'Git blob identity and expected manifest pins do not verify installed native binaries, GPU behavior, signing, license approval or equivalent transcription.',
    'AST edges cover JavaScript/TypeScript module syntax and explicit audited loaders. Native C++, embedded source strings and computed resource paths require the recorded manual audits.',
    'No userData, private audio, model/VAD/CUDA archive or ignored staging artifact is read. No old business module, frontend service or native code is executed.',
    'Destinations are unique proposals only. No copied-file hash or successful native replay is asserted.',
    'Proposed names may be adjusted by the subsequent reviewed copy task; reference-only historical tools and their consumers need explicit replacement or omission before copying tests.',
  ],
};
