import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeAll, describe, expect, it } from 'vitest';
import { createRuntimeWindowsCopyPlan, applyRuntimeWindowsCopyPlan } from '../../scripts/subtitle-studio-provenance/runtime-windows-copy.mjs';
import { RUNTIME_WINDOWS_COPY_RECIPE } from '../../scripts/subtitle-studio-provenance/runtime-windows-copy-recipe.mjs';

const roots: string[] = [];
afterEach(() => { for (const root of roots.splice(0)) fs.rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); });
let plan: ReturnType<typeof createRuntimeWindowsCopyPlan>;
beforeAll(() => { plan = createRuntimeWindowsCopyPlan(); });

describe('T07 independent Windows runtime derivation', () => {
  it('replays the six fixed sources without changing older recipes or destination bytes', () => {
    expect(plan.files).toHaveLength(6);
    expect(applyRuntimeWindowsCopyPlan(plan).sourceCommit).toBe('3a0f50ed15c1b63451402cecf27240182235e567');
    expect(createRuntimeWindowsCopyPlan()).toEqual(plan);
    for (const file of plan.files) {
      expect(file.destinationPath).toMatch(/^scripts\/subtitle-studio\/transcription\/runtime\//);
      expect(file.bytes.toString()).not.toMatch(/(?:from|import\()\s*["'][^"']*local-subtitle\//);
    }
  });
  it('rejects source identity and exact transformation drift', () => {
    const wrongSource = structuredClone(RUNTIME_WINDOWS_COPY_RECIPE);
    wrongSource.sourceCommit = '0'.repeat(40);
    expect(() => createRuntimeWindowsCopyPlan({ recipe: wrongSource })).toThrow(/source commit differs/);
    const wrongEdit = structuredClone(RUNTIME_WINDOWS_COPY_RECIPE);
    wrongEdit.files[0].edits[0].count++;
    expect(() => createRuntimeWindowsCopyPlan({ recipe: wrongEdit })).toThrow(/edit count differs/);
  });
  it('rejects source overwrite and unsafe new output paths', () => {
    for (const destinationPath of ['../escape.mjs', RUNTIME_WINDOWS_COPY_RECIPE.files[0].sourcePath]) {
      const recipe = structuredClone(RUNTIME_WINDOWS_COPY_RECIPE);
      recipe.files[0].destinationPath = destinationPath;
      expect(() => createRuntimeWindowsCopyPlan({ recipe })).toThrow(/Unsafe|Conflicting/);
    }
  });
  it('preserves local destination edits and does not publish provenance over them', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'studio-win-copy-')); roots.push(root);
    const destination = path.join(root, plan.files[0].destinationPath);
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, 'user work');
    expect(() => applyRuntimeWindowsCopyPlan(plan, { root, write: true, provenancePath: 'fork.json' })).toThrow(/destination differs/);
    expect(fs.readFileSync(destination, 'utf8')).toBe('user work');
    expect(fs.existsSync(path.join(root, 'fork.json'))).toBe(false);
  });
  it('rejects changed generated bytes and changed provenance instead of repairing them', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'studio-win-copy-')); roots.push(root);
    applyRuntimeWindowsCopyPlan(plan, { root, write: true, provenancePath: 'fork.json' });
    const destination = path.join(root, plan.files[0].destinationPath);
    fs.appendFileSync(destination, '\n');
    expect(() => applyRuntimeWindowsCopyPlan(plan, { root, provenancePath: 'fork.json' })).toThrow(/destination differs/);
    fs.writeFileSync(destination, plan.files[0].bytes);
    fs.writeFileSync(path.join(root, 'fork.json'), '{}');
    expect(() => applyRuntimeWindowsCopyPlan(plan, { root, provenancePath: 'fork.json' })).toThrow(/destination differs/);
  });
});
