import type { AutomaticKnowledgeRecheckSeed } from '@/subtitle-studio/automatic-knowledge-report-contract';

/** A click-owned handoff, never regenerated by document polling. */
export type AutomaticKnowledgeRecheckRequest = {
  requestId: string;
  documentId: string;
  trackId: string;
  seed: AutomaticKnowledgeRecheckSeed;
  restoreFocus: () => void;
};
